config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :works
  devise_for :users, :controllers => { :registrations => 'user_registrations' }

  devise_scope :user do
    get 'users/myworks' => 'works#user_works', as: :user_works
    get 'users/register' => 'users#register', as: :user_register

    get 'participant/sign_up' => 'user_registrations#new', :user => { :meta_type => 'participant' }, as: :new_participant
    get 'jury/sign_up' => 'user_registrations#new', :user => { :meta_type => 'jury' }, as: :new_jury
  end

  resources :users, only: :show

  get '/works/:id/rating' => 'works#set_rating', as: :rating
  post '/works/:id/rating' => 'works#set_rating', as: :ratingpost
  get '/cat/:category_id' =>  'works#update_works', as: :fetch_items
  get '/categories/:category_id' => 'categories#show', as: :categories
  get '/top/(:category_id)' => 'works#top', as: :top
  get '/works/:id/detailed_rating' => 'works#detailed_rating', as: :detailed

  root 'home#index'
  get 'juries' => 'home#juries', as: :juries_list

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :work
  belongs_to :criterion

  validates :size, numericality: { only_integer: true, greater_than: 0, less_than: 11 }

  scope :was_rait, ->(work, user) { where("user_id=?", user.id).where("work_id=?", work.id) }
end

app/views/rating/_form.html.haml
.row
  .col.s12.m6.l6.offset-m3.offset-l3
    .card-panel
      = form_tag controller: "works", action: "set_rating"
      - @criterions.each do |criterion|
        %p= criterion.name
        = select_tag "size[#{criterion.id}]", options_for_select((1..10).step(1))
      .center
        = submit_tag 'Оценить', data: { confirm: 'Это окончательный вариант оценки?' }, class: 'btn'

app/views/rating/_new.html.haml
%h3#rating.center Оценивание
= render 'rating/form'

app/views/rating/detailed.html.haml
.container
  .row
    .col.s12.m12.l8.offset-l2
      %p.flow-text
        ='Оценки работы "'
        =link_to @work.name, work_path(@work)
        ='"'
      %span.grey-text= "Проголосовало #{@rait.count} из #{User.count_jury}"
  .row
    .col.s12.m12.l8.offset-l2
      %ul.collapsible{data: {collapsible: 'accordion'}}
        - @rait.each do |rait|
          %li
            .collapsible-header.row
              .col.s6
                = rait[:user].last_name + ' ' + rait[:user].first_name + ' ' + rait[:user].meta.middle_name
                %br
                %span.grey-text= '(' + rait[:user].institution + ', ' + rait[:user].meta.degree + ', ' + rait[:user].meta.rank + ')'
              .col.s6.center.rating
                = (decimals(rait[:rating]) > 3 ? rait[:rating].round(3) : rait[:rating])
            .collapsible-body
              - i = 1
              - rait[:detail].each do |d|
                .row
                  .col.s6
                    .cr_name= "#{i}. #{d[:cr_name]}"
                  .col.s6.center
                    .cr_size= d[:cr_size]
                - i = i + 1

app/views/rating/result.html.haml
.row
  .col.s12.m6.l4.offset-m3.offset-l4
    .card-panel
      %h4.center= "Средняя оценка от вас"
      .circular-bar
        %input.dial{"data-fgcolor": "#e74c3c", "data-height": "150", "data-linecap": "round", "data-width": "150", "data-step": "0.1", type: "text", value: "#{decimals(@rait) > 0 ? @rait.round(3) : @rait}"}
        .circular-bar-content
          %strong
      %h4.center= "Общая средняя"
      .circular-bar
        %input.dial{"data-fgcolor": "#34495e", "data-height": "150", "data-linecap": "round", "data-width": "150", "data-step": "0.1", type: "text", value: "#{decimals(@allrait) > 0 ? @allrait.round(3) : @allrait}"}
        .circular-bar-content
          %strong
      .center
        = link_to "перейти к работе", work_path(@work), class: "btn waves-effect waves-light"