config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :works
  devise_for :users, :controllers => { :registrations => 'user_registrations' }

  devise_scope :user do
    get 'users/myworks' => 'works#user_works', as: :user_works
    get 'users/register' => 'users#register', as: :user_register

    get 'participant/sign_up' => 'user_registrations#new', :user => { :meta_type => 'participant' }, as: :new_participant
    get 'jury/sign_up' => 'user_registrations#new', :user => { :meta_type => 'jury' }, as: :new_jury
  end

  resources :users, only: :show

  get '/works/:id/rating' => 'works#set_rating', as: :rating
  post '/works/:id/rating' => 'works#set_rating', as: :ratingpost
  get '/cat/:category_id' =>  'works#update_works', as: :fetch_items
  get '/categories/:category_id' => 'categories#show', as: :categories
  get '/top/(:category_id)' => 'works#top', as: :top
  get '/works/:id/detailed_rating' => 'works#detailed_rating', as: :detailed

  root 'home#index'
  get 'juries' => 'home#juries', as: :juries_list

end

app/models/work.rb
class Work < ActiveRecord::Base
  paginates_per 12

  belongs_to :user
  belongs_to :category
  has_many :ratings, dependent: :destroy
  has_many :images, dependent: :destroy

  has_attached_file :file, styles: { medium: "600x600", thumb: "300x300#" }, default_url: ""
  validates_attachment :file, presence: true
  validates_attachment_content_type :file, content_type: /\Aimage\/.*\Z/

  validates :name, length: { in: 3..30 }
  validates :description, length: { in: 10..1000 }

  validates :name, :description, :category, :archive_url, presence: true

  validates :archive_url, url: true

  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true

  resourcify

  def count_jury
    self.ratings.select(:user_id).uniq.count
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy, :set_rating, :detailed_rating]
  before_action :authenticate_user!, except: [:index, :show, :top, :detailed_rating]
  # before_action :authorized_user, only: [:edit, :update, :destroy]

  authorize_resource only: [:create, :edit, :update, :destroy]

  def user_works
    @works = current_user.works.order('created_at DESC').page(params[:page])
    render 'works/myworks'
  end

  def detailed_rating
    @rait = []
    @work.ratings.select('user_id').uniq.each do |rating|
      detail = []
      @work.ratings.where('user_id = ?', rating.user).each do |r|
        detail << {cr_name: r.criterion.name, cr_size: r.size}
      end
      @rait << {user: rating.user, rating: Rating.was_rait(@work, rating.user).all.average(:size), detail: detail}
    end

    render 'rating/detailed'
  end

  def set_rating
    authorize! :set_rating, @work
    unless Rating.was_rait(@work, current_user).empty?
      redirect_to work_path(@work), alert: 'Вы уже оценили'
      return
    end
    @criterions = Criterion.all
    if request.get?
      render 'works/show'
    else
      params[:size].each do |val|
        unless val[1].to_i.between?(1,10)
          redirect_to @work, alert: 'Неверное значение оценки (корректные от 1 до 10)'
          return
        end
      end
      params[:size].each do |i, val|
        @rating = Rating.new
        @rating.user = current_user
        @rating.work = @work
        @rating.criterion = Criterion.find(i)
        @rating.size = val
        @rating.save
      end
      @rait = Rating.was_rait(@work, current_user).all.average(:size)
      @allrait = @work.ratings.all.average(:size)
      render 'rating/result'
    end
  end

  # GET /top
  def top
    @works = Work.joins(:ratings).uniq
                 .select('works.*, avg(ratings.size) as rait')
                 .group('works.id')
                 .having('count(distinct ratings.user_id) = ?', User.count_jury)
                 .order('rait DESC')
                 .limit(10)
    @works = @works.where('category_id=?', params[:category_id]) if params.has_key? :category_id

    render 'works/top'
  end

  # GET /works
  # GET /works.json
  def index
    @works = Work.all.order('created_at DESC').page(params[:page])

    # if request.xhr?
    #   render partial: "work", collection: @works
    # end
  end

  def update_works
    @works = Work.where('category_id=?', params[:category_id]).order('created_at DESC').all
    if !@works.empty?
      render partial: 'partials/work', collection: @works
    else
      render partial: 'partials/nothing'
    end
  end

  # GET /works/1
  # GET /works/1.json
  def show

  end

  # GET /works/new
  def new
    @work = current_user.works.build
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = current_user.works.build(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Работа создана успешно' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Работа обновлена' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Работа успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
      @allrait = @work.ratings.all.average(:size)
    end

    def authorized_user
      @work = current_user.works.find_by(id: params[:id])
      redirect_to works_path, notice: 'Вы не авторизованы' if @work.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(
          :name, :description, :user_id, :category_id, :file, :archive_url,
          images_attributes: [ :image, :_destroy, :id ])
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.haml
.row
  .col.s12.m6.l6.offset-m3.offset-l3
    .card-panel
      = form_for(@work) do |f|
        .row
          - if @work.errors.any?
            #error_explanation
              .col.s12
                Ошибка добавления:
                %ul
                  - @work.errors.full_messages.each do |message|
                    %li= message
          .input-field.col.s12
            = f.label :name, 'Название'
            = f.text_field :name
          .input-field.col.s12
            = f.text_area :description, class: 'materialize-textarea'
            = f.label :description, 'Описание'
          .input-field.col.s12
            = f.select :category_id, Category.all.collect {|a| [a.name, a.id]}
            = f.label :category_id, 'Категория'
          .input-field.col.s12
            = f.label :archive_url, 'Ссылка на архив'
            = f.text_field :archive_url
          - if @work.file.exists?
            = image_tag @work.file.url(:thumb), class: 'col s12 m12 l4', height: '200px'
          .file-input.col.s12
            = f.label :file, 'Основной скриншот'
            = f.file_field :file
          .file-input.col.s12
            = f.label :file, 'Дополнительные скриншоты'
            = render partial: 'image_edit', collection: @work.images, locals: { builder: f }
            = link_to_add_fields('Добавить скрин', f, 'images')
          -#.file-field.input-field.col.s12
          -#  .btn
          -#    %span Скрин
          -#    = f.file_field :file
          -#  .file-path-wrapper.col.s12.right
          -#    = f.text_field :file, class: 'file-path validate'
          .input-field.col.s12.center
            = f.submit (@work.new_record? ? 'Добавить' : 'Редактировать'), class: 'btn'

app/views/works/_image_edit.html.haml
= builder.fields_for(:images, image_edit) do |f|
  .image-field
    %p= image_tag image_edit.image.url(:thumb)
    %p
      = f.hidden_field :_destroy
      = link_to 'Удалить', '#', class: 'remove_fields'

app/views/works/_image_fields.html.haml
.image-field
  .input-field.col.s12
    = f.file_field :image
  .input-field.col.s12
    = f.hidden_field :_destroy
    = link_to 'Удалить поле', '#', class: 'remove_fields'

app/views/works/edit.html.haml
%h3.center Редактирование работы
= render 'form'
-#= link_to 'Show', @work
-#|
= link_to 'Назад', works_path

app/views/works/index.html.haml
.container
  - unless current_page? controller: 'works', action: 'user_works'
    .row#category
      .input-field.col.s12.m12.l12
        = select_tag "categories", options_for_select(Category.all.collect {|a| [a.name + " ( #{ a.works.count } )", a.id]}), {prompt: "ВСЕ РАБОТЫ ( #{Work.count} )", onchange: "update_works_div(this.value)", class: "browser-default"}
  .row#works
    - if !@works.empty?
      = render partial: "partials/work", collection: @works
    - else
      = render partial: "partials/nothing"
  #paginator
    = paginate @works
//= link_to 'New Work', new_work_path

app/views/works/index.js.haml
$('#works').html("#{escape_javascript(render partial: "partials/work", collection: @works)}");
$('#paginator').html("#{escape_javascript(paginate(@works, :remote => true)) }");

app/views/works/myworks.html.haml
%section.container
  .section
    .row
      %h4.col.s12.center Мои работы
    .row
      - if !@works.empty?
        = render partial: "partials/work", collection: @works
      - else
        = render partial: "partials/nothing"
    #paginator
      = paginate @works

app/views/works/new.html.haml
%h3.center Добавление работы
= render 'form'
-#= link_to 'Назад', works_path

app/views/works/show.html.haml
.container.work
  .row
    %h4.name= @work.name
    %p.date
      %i.mdi-action-today.prefix
      =l @work.created_at, format: :my
    .col.s12.m12.l6
      .card
        .center
          = image_tag @work.file.url(:medium), class: 'responsive-img', height: '400'
      - if @work.images.any?
        .card
          - @work.images.each do |image|
            .col.s6.m3.l3.center
              =link_to image_tag(image.image.url(:thumb), class: 'responsive-img small-preview'), image.image.url(:original), {'data-lightbox': 'roadtrip'}
    .col.s12.m12.l6
      .card-panel.grey.lighten-5.work-info
        - if current_user
          .row
            .col.s12.m6.offset-m3.center
              - if can? :set_rating, @work and Rating.was_rait(@work, current_user).empty?
                .card
                  = link_to 'Оценить', work_path(@work)+'/rating#rating', class: 'btn-flat waves-effect waves-teal'
              - if current_user and current_user.has_role? :jury
                .card
                  = link_to 'Скачать архив', @work.archive_url, class: 'btn-flat waves-effect waves-teal', rel: 'noopener noreferrer', target: '_blank'
              - if can? :update, @work and can? :destroy, @work
                = link_to '<i class="material-icons">edit</i>'.html_safe, edit_work_path(@work), class: 'btn waves-effect waves-teal', title: 'Редактировать'
                = link_to '<i class="material-icons">delete_forever</i>'.html_safe, @link, method: :delete, data: { confirm: 'Серьезно?' }, class: 'btn waves-effect waves-teal', title: 'Удалить'
        %p.work-info__author
          %i.material-icons person
          = link_to @work.user.first_name + ' ' + @work.user.last_name, user_path(@work.user)
        %p.work-info__categ
          %i.material-icons label
          = link_to @work.category.name, categories_path(@work.category)
        %p= simple_format @work.description
      .card-panel
        %h5.rating-header.center= 'Общая оценка'
        =link_to detailed_path do
          .circular-bar.tooltipped{'data-position':'top', 'data-delay': '50', 'data-tooltip': "Проголосовало #{@work.count_jury} из #{User.count_jury}"}
            %input.dial{"data-fgcolor": '#34495e', "data-height": '150', "data-linecap": "round", "data-width": "150", "data-step": "0.1", type: "text", value: "#{(decimals(@allrait) > 3 ? @allrait.round(3) : @allrait) unless @allrait.nil?}"}
            .circular-bar-content
              %strong
  = render 'rating/new' if current_page? action: 'set_rating'

app/views/works/top.html.haml
.container
  .row
    .col.s12.m12.l8.offset-l2
      - if @works.blank?
        .card-panel.center.flow-text= 'К сожалению, пока нет работ, за которые проголосовали все члены жюри'
      - else
        .row#category
          .input-field.col.s12
            = select_tag "categories", options_for_select(Category.all.collect {|a| [a.name, a.id]}), {prompt: "ВСЕ РАБОТЫ", onchange: "update_works_div_top(this.value)", class: "browser-default"}
        .row#works
          - i = 0
          - @works.each do |work|
            - i = i + 1
            .row.card-panel.top-work{class: ("teal lighten-4" if i==1)}
              .row.top-title
                .col.s12
                  %h5
                    %b= i.to_s + ". " + work.name
                  %span= link_to work.user.first_name + " " + work.user.last_name, user_path(work.user)
              .col.s6.m3.l3
                .card.small
                  .card-image
                    = link_to (image_tag work.file.url(:thumb)), work_path(work)
              .col.s6.m3.l3.right
                .circular-bar
                  %input.dial{"data-fgcolor": "#34495e", "data-height": "100", "data-linecap": "round", "data-width": "100", "data-step": "0.1", type: "text", value: "#{decimals(work.rait) > 3 ? work.rait.round(3) : work.rait}"}
                  .circular-bar-content
                    %strong