config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :works
  devise_for :users, :controllers => { :registrations => 'user_registrations' }

  devise_scope :user do
    get 'users/myworks' => 'works#user_works', as: :user_works
    get 'users/register' => 'users#register', as: :user_register

    get 'participant/sign_up' => 'user_registrations#new', :user => { :meta_type => 'participant' }, as: :new_participant
    get 'jury/sign_up' => 'user_registrations#new', :user => { :meta_type => 'jury' }, as: :new_jury
  end

  resources :users, only: :show

  get '/works/:id/rating' => 'works#set_rating', as: :rating
  post '/works/:id/rating' => 'works#set_rating', as: :ratingpost
  get '/cat/:category_id' =>  'works#update_works', as: :fetch_items
  get '/categories/:category_id' => 'categories#show', as: :categories
  get '/top/(:category_id)' => 'works#top', as: :top
  get '/works/:id/detailed_rating' => 'works#detailed_rating', as: :detailed

  root 'home#index'
  get 'juries' => 'home#juries', as: :juries_list

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= "IT олимпиада"
    %meta{charset: "utf-8"}/
    / Let browser know website is optimized for mobile
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", name: "viewport"}/
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": true
    = stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons"
    = csrf_meta_tags
  %body{class: "body-#{controller_name}"}

    - if User.not_active_jury.include?(current_user)
      .container
        .row
          .col.s12.toast.orange
            .center-block.center= 'Дождитесь пока администратор подтвердит, что вы жюри'

    %header.main-bag
      -if user_signed_in?
        %ul#dropdown1.dropdown-content
          - if can? :create, Work and !User.not_active_jury.include?(current_user)
            %li
              =link_to 'Добавить работу', new_work_path
            %li
              =link_to 'Мои работы', user_works_path
          %li
            =link_to 'Аккаунт', edit_user_registration_path()
          %li
            =link_to 'Выход', destroy_user_session_path
      %nav{role: 'navigation'}
        .nav-wrapper.container
          %a{href: '/', class: 'logo'}
            = inline_svg "sports.svg", size: '100%'
          %a.button-collapse.right{'data-activates': 'nav-mobile', href: '#'}
            %i.mdi-navigation-menu
          - unless user_signed_in?
            %ul.right.hide-on-med-and-down
              %li
                =link_to 'работы', works_path, class: 'nav-el'
              %li
                =link_to 'жюри', juries_list_path, class: 'nav-el'
              %li
                =link_to 'Вход', new_user_session_path, class: 'nav-el'
              %li
                =link_to 'Регистрация', user_register_path, class: 'nav-el'
              %li
                =link_to 'Топ 10', top_path, class: 'btn red waves-effect'
            %ul#nav-mobile.side-nav
              %li
                =link_to 'Вход', new_user_session_path, class: 'nav-el'
              %li
                =link_to 'Регистрация', user_register_path, class: 'nav-el'
              %li
                =link_to 'работы', works_path, class: 'btn teal waves-effect'
              %li
                =link_to 'жюри', juries_list_path, class: 'btn teal waves-effect'
              %li
                =link_to 'Топ 10', top_path, class: 'btn red waves-effect'
          - else
            %ul.right.hide-on-med-and-down
              %li
                =link_to 'работы', works_path, class: 'nav-el'
              %li
                =link_to 'жюри', juries_list_path, class: 'nav-el'
              %li
                %a.nav-el.dropdown_menu_button{href: "#!", "data-activates": "dropdown1" }
                  = current_user.first_name
                  %i.mdi-navigation-arrow-drop-down.right
              %li
                =link_to 'Топ 10', top_path, class: 'btn red waves-effect'
            %ul#nav-mobile.side-nav
              %li
                %a.dropdown-button{href: "#!", "data-activates": "dropdown2", class: "nav-el"}
                  = current_user.first_name
                  %i.mdi-navigation-arrow-drop-down.right
              %li
                =link_to 'работы', works_path, class: 'btn teal waves-effect'
              %li
                =link_to 'жюри', juries_list_path, class: 'btn teal waves-effect'
              %li
                =link_to 'Топ 10', top_path, class: 'btn red waves-effect'
              %ul#dropdown2.dropdown-content
                - if can? :create, Work and !User.not_active_jury.include?(current_user)
                  %li
                    =link_to 'Добавить работу', new_work_path
                  %li
                    =link_to 'Мои работы', user_works_path
                %li
                  =link_to 'Аккаунт', edit_user_registration_path
                %li
                  =link_to 'Выход', destroy_user_session_path
      .container
        .row
          .col.m12
            .header
              %h1.valign.grey-text.text-lighten-5 Дистанционная олимпиада по информационным технологиям
              -#%a#scroll.valign.btn-large.btn-floating.materialize-red.lighten-2.waves-effect.waves-light{:href => '#works'}
                %i.mdi-navigation-expand-more
    %main
      = yield
    -#- if current_page?(root_url)
    %footer.page-footer.teal.lighten-1
      .footer-copyright
        .container.center
          From VPI with
          %i.mdi-action-favorite
    = javascript_include_tag "application", "data-turbolinks-track": true

    - unless flash.empty?
      -flash.each do |key, f|
        - if key == "alert"
          :javascript
            Materialize.toast('#{f}', 4000, 'red')
        - else
          :javascript
            Materialize.toast('#{f}', 4000)